on:
  repository_dispatch:
    types: [build-release-holochain]

jobs: 
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platforms: 
          - host: macos-11
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-20.04
            target: x86_64-apple-darwin
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
    runs-on: ${{ matrix.platforms.host }}
    steps:
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
      - name: install Go stable
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: install dependencies (ubuntu only)
        if: matrix.platforms.host == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev
      - uses: actions/checkout@v4
        with:
          repository: holochain/holochain
          ref: ${{ github.event.client_payload.holochain_ref }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin holochain --bin hc
      - name: Rename artifact
        run: |
          mv target/release/holochain target/release/holochain-${{ matrix.platforms.target }}
          mv target/release/hc target/release/hc-${{ matrix.platforms.target }}
      - name: Upload artifacts (unix paths)
        if: matrix.platforms.host == 'ubuntu-20.04' || matrix.platforms.host == 'macos-11'
        uses: actions/upload-artifact@v3
        with:
          path: |
            target/release/holochain-*
            target/release/hc-*
          if-no-files-found: error
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact/holochain-*, artifact/hc-*"
          name: Holochain - ${{ github.event.client_payload.ref }}
          body: "Holochain binaries built from ${{ github.event.client_payload.ref }}"
          tag: "holochain-${{ github.event.client_payload.ref }}"
          draft: true
          prerelease: false
          skipIfReleaseExists: true