on:
  repository_dispatch:
    types: [new_holochain_release]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - system: x86_64-darwin
          - system: aarch64-darwin
          - system: x86_64-linux
    steps:
      - uses: actions/checkout@v4
        with:
          repository: holochain/holochain
          ref: ${{ github.event.client_payload.ref }}
      - name: "Build"
        env:
          system: ${{ matrix.platform.system }}
        run: |
          nix develop --command bash -c "cargo build --target ${{ matrix.platform.system }} --release --bin holochain --bin hc --bin lair-keystore"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Holochain Prebuilt Binaries - ${{ github.event.client_payload.ref }}
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}